targets:
  $default:
    builders:
      ferry_generator|graphql_builder:
        enabled: true
        options:
          schema: sleek_travel_frontend|lib/graphql/schema.graphql
      ferry_generator|serializer_builder:
        enabled: true
        options:
          schema: sleek_travel_frontend|lib/graphql/schema.graphql
          custom_serializers:
            - import: "package:sleek_travel_frontend/model/bigint_serializer.dart"
              name: GBigIntSerializer
